### ISSUE TITLE
Image does not exist

### ISSUE THREAD

**Issue by Blarc** [withastro/blog-tutorial-demo#1]
Image url in `post-4.md`:
https://github.com/withastro/blog-tutorial-demo/blob/ed705d633b414eaeb082bfce4c3c36137156719d/src/pages/posts/post-4.md?plain=1#L7
does not exist (https://astro.build/assets/hero_NkT0b.avif).

**Comment by sarah11918** [comment]
Thank you for this! We'll get that image updated. 🚀

**Comment by sarah11918** [comment]
@delucis - We could use https://astro.build/assets/cover_OyvDH.avif instead?

**Comment by Jutanium** [comment]
Fixed!
