### ISSUE TITLE
Changing the theme from Dark Mode to Light Mode

### ISSUE THREAD

**Issue by intincrab** [withastro/blog-tutorial-demo#13]
I ran the end project on Stackblitz it is also giving those weird flashes in dark mode.
[Stackblitz ](https://stackblitz.com/github/withastro/blog-tutorial-demo/tree/complete?file=src/pages/index.astro )

I also ran this on my local machine in Chrome and Firefox also.

Preview:
![Withastro_-_Blog_Tutorial_Demo_-_StackBlitz_Mozilla_Firefox_2023-04-30_19-21-13_online-video-cutter com](https://github.com/withastro/blog-tutorial-demo/assets/93028153/52ca48ad-e677-4953-8ddc-07d703cdcb4a)

Possible Solution: 
Adding the` is:inline` in the script tag of the ThemeIcon.astro

**Comment by ElianCodes** [comment]
Hey! Thanks for opening this issue! We solved this in our upgrade to Astro v3
