### ISSUE TITLE
[after upgraded to v3] Try to add ViewTransitions!

### ISSUE THREAD

**Issue by sarah11918** [withastro/blog-tutorial-demo#23]
We are *not* going to add view transitions to this project, nor the tutorial itself.

BUT, we would like to ensure that the project will *work* if someone who takes it then wants to add View Transitions themselves.

So, once the project has been upgraded to v3.x, and once we are happy with the theme toggle and hamburger menu (which are the things that might have trouble with view transitions?), try adding it and see whether it can be successfully done.

Please report any issues you had doing so, or changes you needed to make to get it to work.  We could eventually turn this into an "Add View Transitions to the Build a Blog Tutorial!" the same way we have done for content collections.

**Comment by ElianCodes** [comment]
It Works!
