### ISSUE TITLE
[theme toggle] div -> button

### ISSUE THREAD

**Issue by sarah11918** [withastro/blog-tutorial-demo#4]
Making a note so we don't forget! @Jutanium @delucis 

This PR https://github.com/withastro/docs/pull/2616 will need us to update both the final and content collections branch here!

**Comment by Jutanium** [comment]
I already made this change!

**Comment by delucis** [comment]
Yup, confirming: https://github.com/withastro/blog-tutorial-demo/commit/825b89664879a407b147d518e7c5f5529c4b2446
