### ISSUE TITLE
Update broken asset links

### ISSUE THREAD

**Issue by BryceRussell** [withastro/blog-tutorial-demo#7]
This PR: https://github.com/withastro/docs/pull/3016 in the docs repo updates all `astro.build/assets` links to new `docs.astro.build/assets` links. The links/assets in the PR are temporary until dedicated assets can be made. Once the dedicated assets have been created all branches in this repo will need updates to their asset links to reflect the changes in the docs repo.

**Comment by rodneytamblyn** [comment]
The above PR is merged, but the image links in the blog posts are still all broken, e.g.
https://astro.build/assets/blog/astro-1-release-update/cover.jpeg

![image](https://github.com/withastro/blog-tutorial-demo/assets/1562956/518a9212-f8ce-4dd3-a3c1-8d1ca79f511d)

**Comment by BryceRussell** [comment]
@rodneytamblyn The asset links in the PR mentioned above are temporary to make sure there are no dead links inside the docs. Right now, we are waiting on custom assets for the tutorial before updating the links in this repo (and the docs) with more permanent links.
